In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df=pd.read_csv('ML-Om1.csv')
# print(df.to_string())
df.head

<bound method NDFrame.head of            id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0  

**PM1**



In [4]:
dfPM1=df.dropna()
print(df.shape, dfPM1.shape)

(569, 32) (563, 32)


In [5]:
data=dfPM1.values.tolist()
data=np.array(data)
# print(data)
X=data[:,2:]
Y=data[:,1:2]
# print(X)
for i in Y:
  if i[0]=='M': # Malignant=1; Benign = 0
    i[0]=1
  else:
    i[0]=0
# print(Y)

In [6]:
X = X.astype('float64')
Y = Y.astype('float64')
print(X.shape, Y.shape)
print(X.dtype,Y.dtype)

(563, 30) (563, 1)
float64 float64


In [7]:
split_ratio=0.67
split_rows=int(np.floor(0.67*X.shape[0]))
X_train=X[:split_rows+1]
X_test=X[split_rows+1:]
Y_train=Y[:split_rows+1]
Y_test=Y[split_rows+1:]
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(378, 30) (185, 30) (378, 1) (185, 1)


In [8]:
class Perceptron():
  
  def __init__(self):
    pass

  def train_model(self, X, Y, n, iters): # n = learning rate
    no_cols = X.shape[1]
    self.w = np.zeros((no_cols,1))
    macc=0
    for _ in range(iters):
      # a = np.dot(X, self.w)
      # y_predicted = self.activation(a)
      for i in range(X.shape[0]):

        k=X[i].reshape(1,30)
        yp=self.predict(k)
        y_predicted = self.predict(X)

        # dw=n*np.dot(X.T,(y-y_predicted))
        emac=macc
        macc= max(macc,100-np.mean(np.abs(Y-y_predicted))*100)
        if macc==100-np.mean(np.abs(Y-y_predicted))*100 and emac!=macc:
          print(_,macc)
        if macc==100:
          return self.w
        self.w += (n*np.dot(k.T,(Y[i]-yp)))
    
    return self.w

  def activation(self, a):
    predicted = np.array([1 if x>=0 else 0 for x in a])[:, np.newaxis]
    return predicted

  def predict(self, X):
    a = np.dot(X, self.w)
    y_p = self.activation(a)
    return y_p



In [9]:
Perceptron_Model = Perceptron()

Iteration = [1000]
LR = [0.125, 0.25, 0.45, 0.75, 0.8, 0.9, 0.95, 0.99, 1]
L=[1]

for iters in Iteration:
  w_trained = Perceptron_Model.train_model(X_train, Y_train, 0.75, iters)
  y_predict_train = Perceptron_Model.predict(X_train)
  y_predict_test = Perceptron_Model.predict(X_test)
  print(f"for iterations = {iters}")
  print(f"training accuracy: {100 - np.mean(np.abs(y_predict_train - Y_train)) * 100}%")
  print(f"test accuracy: {100 - np.mean(np.abs(y_predict_test - Y_test)) * 100}%")
  print(" ")

0 44.44444444444444
0 55.55555555555556
0 68.25396825396825
0 91.26984126984127
1 91.53439153439153
6 91.7989417989418
10 92.06349206349206
23 92.32804232804233
90 92.5925925925926
387 92.85714285714286
400 93.12169312169313
for iterations = 1000
training accuracy: 92.5925925925926%
test accuracy: 93.51351351351352%
 


In [17]:
TP=0
FP=0
TN=0
FN=0

for i in range(len(y_predict_test)):
  if y_predict_test[i]==1 and Y_test[i]==1:
    TP+=1
  elif y_predict_test[i]==1 and Y_test[i]==0:
    FP+=1
  elif y_predict_test[i]==0 and Y_test[i]==1:
    FN+=1
  elif y_predict_test[i]==0 and Y_test[i]==0:
    TN+=1
print("Confusion Matrix:")
print(np.array([[TP,FP],[FN,TN]]))
print(" ")
print("For PM1:")
print(" ")
print("Accuracy:", (TP + TN)/(TP + TN + FP + FN))
print("Precision:", TP/(TP + FP))
print("Recall:", TP/(TP + FN))

Confusion Matrix:
[[ 38   7]
 [  5 135]]
 
For PM1:
 
Accuracy: 0.9351351351351351
Precision: 0.8444444444444444
Recall: 0.8837209302325582


**PM2**

In [18]:
dfPM2=df.dropna()
print(df.shape, dfPM2.shape)
print(dfPM2.shape)
dfPM2=dfPM2.sample(frac=1, random_state=50).reset_index()
print(dfPM2.shape)



data=dfPM2.values.tolist()
data=np.array(data)
X=data[:,3:]
Y=data[:,2:3]
for i in Y:
  if i[0]=='M': # Malignant=1; Benign = 0
    i[0]=1
  else:
    i[0]=0

X = X.astype('float64')
Y = Y.astype('float64')
print(X.shape, Y.shape)
print(X.dtype,Y.dtype)

split_ratio=0.67
split_rows=int(np.floor(0.67*X.shape[0]))
X_train=X[:split_rows+1]
X_test=X[split_rows+1:]
Y_train=Y[:split_rows+1]
Y_test=Y[split_rows+1:]
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(569, 32) (563, 32)
(563, 32)
(563, 33)
(563, 30) (563, 1)
float64 float64
(378, 30) (185, 30) (378, 1) (185, 1)


In [19]:
dfPM2.head

<bound method NDFrame.head of      index         id diagnosis  radius_mean  texture_mean  perimeter_mean  \
0      216    8811523         B       11.890         18.35           77.32   
1      110     864033         B        9.777         16.99           62.50   
2      284    8912284         B       12.890         15.70           84.08   
3      203      87880         M       13.810         23.75           91.56   
4      461  911296202         M       27.420         26.27          186.90   
..     ...        ...       ...          ...           ...             ...   
558     70     859575         M       18.940         21.31          123.60   
559    132   86730502         M       16.160         21.54          106.20   
560    289   89143601         B       11.370         18.89           72.17   
561    109     864018         B       11.340         21.26           72.48   
562    480     912193         B       12.160         18.03           78.29   

     area_mean  smoothness_mean  

In [20]:
PM2 = Perceptron()

Iteration = [1000]
LR = [0.125, 0.25, 0.45, 0.75, 0.8, 0.9, 0.95, 0.99, 1]
L=[1]

for iters in Iteration:
  w_trained = PM2.train_model(X_train, Y_train, 0.75, iters)
  y_predict_train = PM2.predict(X_train)
  y_predict_test = PM2.predict(X_test)
  print(f"for iterations = {iters}")
  print(f"training accuracy: {100 - np.mean(np.abs(y_predict_train - Y_train)) * 100}%")
  print(f"test accuracy: {100 - np.mean(np.abs(y_predict_test - Y_test)) * 100}%")
  print(" ")

0 36.772486772486765
0 63.22751322751323
0 64.02116402116403
0 66.66666666666667
0 67.19576719576719
0 88.88888888888889
0 91.26984126984127
0 91.53439153439153
1 92.5925925925926
3 93.12169312169313
157 93.3862433862434
307 93.65079365079364
595 93.91534391534391
for iterations = 1000
training accuracy: 92.32804232804233%
test accuracy: 91.35135135135135%
 


In [21]:
TP=0
FP=0
TN=0
FN=0

for i in range(len(y_predict_test)):
  if y_predict_test[i]==1 and Y_test[i]==1:
    TP+=1
  elif y_predict_test[i]==1 and Y_test[i]==0:
    FP+=1
  elif y_predict_test[i]==0 and Y_test[i]==1:
    FN+=1
  elif y_predict_test[i]==0 and Y_test[i]==0:
    TN+=1
print("Confusion Matrix:")
print(np.array([[TP,FP],[FN,TN]]))
print(" ")
print("For PM2:")
print(" ")
print("Accuracy:", (TP + TN)/(TP + TN + FP + FN))
print("Precision:", TP/(TP + FP))
print("Recall:", TP/(TP + FN))

Confusion Matrix:
[[ 58   2]
 [ 14 111]]
 
For PM2:
 
Accuracy: 0.9135135135135135
Precision: 0.9666666666666667
Recall: 0.8055555555555556


**PM3**

In [22]:
df2=df
for i in df.columns:
  if df2[i].isnull().sum()==0:
    continue
  else:
    n=df.shape[0]-df2[i].isnull().sum()
    meanval=df[i].sum()/n
    df2[i].fillna(value=meanval, inplace=True)


for i in df.columns:
  if i=='id' or i=='diagnosis':
    continue
  else:
    df2[i] = (df2[i] - df2[i].mean())/df2[i].std()
df2.head

<bound method NDFrame.head of            id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M     1.102422     -2.071512        1.268389   0.983510   
1      842517         M     1.836635     -0.353322        1.684639   1.907030   
2    84300903         M     1.586206      0.455786        1.565122   1.557513   
3    84348301         M    -0.767260      0.253509       -0.595257  -0.763792   
4    84358402         M     1.756953     -1.150804        1.775308   1.824624   
..        ...       ...          ...           ...             ...        ...   
564    926424         M     2.118368      0.720838        2.059677   2.341795   
565    926682         M     1.711420      2.083301        1.614577   1.722326   
566    926954         M     0.706858      2.043775        0.670803   0.577445   
567    927241         M     1.845172      2.334403        1.981372   1.733693   
568     92751         B    -1.808817      1.220718       -1.817631  -1.346604  

In [23]:
data=df2.values.tolist()
data=np.array(data)
# print(data)
X=data[:,2:]
Y=data[:,1:2]
for i in Y:
  if i[0]=='M': # Malignant=1; Benign = 0
    i[0]=1
  else:
    i[0]=0

In [24]:
X = X.astype('float64')
Y = Y.astype('float64')
print(X.shape, Y.shape)
print(X.dtype,Y.dtype)

(569, 30) (569, 1)
float64 float64


In [25]:
split_ratio=0.67
split_rows=int(np.floor(0.67*X.shape[0]))
X_train=X[:split_rows+1]
X_test=X[split_rows+1:]
Y_train=Y[:split_rows+1]
Y_test=Y[split_rows+1:]
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(382, 30) (187, 30) (382, 1) (187, 1)


In [26]:
PM3 = Perceptron()

Iteration = [2158] #since it separated at 2157 iterations.
LR = [0.125, 0.25, 0.45, 0.75, 0.8, 0.9, 0.95, 0.99, 1]
L=[1]

for iters in Iteration:
  w_trained = PM3.train_model(X_train, Y_train, 0.75, iters)
  y_predict_train = PM3.predict(X_train)
  y_predict_test = PM3.predict(X_test)
  print(f"for iterations = {iters}")
  print(f"training accuracy: {100 - np.mean(np.abs(y_predict_train - Y_train)) * 100}%")
  print(f"test accuracy: {100 - np.mean(np.abs(y_predict_test - Y_test)) * 100}%")
  print(" ")

0 44.24083769633508
0 82.72251308900523
0 88.48167539267016
0 90.57591623036649
0 91.09947643979058
0 92.14659685863874
0 94.76439790575917
0 95.28795811518324
0 96.8586387434555
0 97.64397905759162
3 97.90575916230367
5 98.16753926701571
12 98.42931937172774
14 98.69109947643979
33 98.95287958115183
38 99.21465968586388
334 99.47643979057591
870 99.73821989528795
2157 100.0
for iterations = 2158
training accuracy: 100.0%
test accuracy: 92.51336898395722%
 


In [27]:
TP=0
FP=0
TN=0
FN=0

for i in range(len(y_predict_test)):
  if y_predict_test[i]==1 and Y_test[i]==1:
    TP+=1
  elif y_predict_test[i]==1 and Y_test[i]==0:
    FP+=1
  elif y_predict_test[i]==0 and Y_test[i]==1:
    FN+=1
  elif y_predict_test[i]==0 and Y_test[i]==0:
    TN+=1
print("Confusion Matrix:")
print(np.array([[TP,FP],[FN,TN]]))
print(" ")
print("For PM3:")
print(" ")
print("Accuracy:", (TP + TN)/(TP + TN + FP + FN))
print("Precision:", TP/(TP + FP))
print("Recall:", TP/(TP + FN))

Confusion Matrix:
[[ 40  11]
 [  3 133]]
 
For PM3:
 
Accuracy: 0.9251336898395722
Precision: 0.7843137254901961
Recall: 0.9302325581395349


**PM4**

In [28]:
df=pd.read_csv('ML-Om1.csv')
# print(df.to_string())
df.head

<bound method NDFrame.head of            id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0  

In [29]:
dfdf=df.dropna()
dfdf=dfdf.sample(frac=1, axis=1)
dfdf=dfdf.drop(['id'],axis=1)

Ydf=dfdf['diagnosis']
Xdf=dfdf.drop(['diagnosis'],axis=1)
print(Xdf.shape, Ydf.shape)

(563, 30) (563,)


In [30]:
X=np.array(Xdf)
Y=np.array(Ydf).reshape(X.shape[0],1)
print(X.shape,Y.shape)

(563, 30) (563, 1)


In [31]:
for i in Y:
  if i[0]=='M': # Malignant=1; Benign = 0
    i[0]=1
  else:
    i[0]=0

X = X.astype('float64')
Y = Y.astype('float64')
print(X.shape, Y.shape)
print(X.dtype,Y.dtype)

split_ratio=0.67
split_rows=int(np.floor(0.67*X.shape[0]))
X_train=X[:split_rows+1]
X_test=X[split_rows+1:]
Y_train=Y[:split_rows+1]
Y_test=Y[split_rows+1:]
print(X_train.shape,X_test.shape,Y_train.shape,Y_test.shape)

(563, 30) (563, 1)
float64 float64
(378, 30) (185, 30) (378, 1) (185, 1)


In [32]:
PM4 = Perceptron()

Iteration = [1000]
LR = [0.125, 0.25, 0.45, 0.75, 0.8, 0.9, 0.95, 0.99, 1]
L=[1]

for iters in Iteration:
  w_trained = PM4.train_model(X_train, Y_train, 0.75, iters)
  y_predict_train = PM4.predict(X_train)
  y_predict_test = PM4.predict(X_test)
  print(f"for iterations = {iters}")
  print(f"training accuracy: {100 - np.mean(np.abs(y_predict_train - Y_train)) * 100}%")
  print(f"test accuracy: {100 - np.mean(np.abs(y_predict_test - Y_test)) * 100}%")
  print(" ")

0 44.44444444444444
0 55.55555555555556
0 68.25396825396825
0 91.26984126984127
1 91.53439153439153
6 91.7989417989418
10 92.06349206349206
23 92.32804232804233
90 92.5925925925926
387 92.85714285714286
400 93.12169312169313
for iterations = 1000
training accuracy: 92.5925925925926%
test accuracy: 93.51351351351352%
 


In [33]:
TP=0
FP=0
TN=0
FN=0

for i in range(len(y_predict_test)):
  if y_predict_test[i]==1 and Y_test[i]==1:
    TP+=1
  elif y_predict_test[i]==1 and Y_test[i]==0:
    FP+=1
  elif y_predict_test[i]==0 and Y_test[i]==1:
    FN+=1
  elif y_predict_test[i]==0 and Y_test[i]==0:
    TN+=1
print("Confusion Matrix:")
print(np.array([[TP,FP],[FN,TN]]))
print(" ")
print("For PM4:")
print(" ")
print("Accuracy:", (TP + TN)/(TP + TN + FP + FN))
print("Precision:", TP/(TP + FP))
print("Recall:", TP/(TP + FN))

Confusion Matrix:
[[ 38   7]
 [  5 135]]
 
For PM4:
 
Accuracy: 0.9351351351351351
Precision: 0.8444444444444444
Recall: 0.8837209302325582
